api/pom.xml
api/src/main/java/org/openmrs/module/kenyaemrml/MLinKenyaEMRActivator.java
api/src/main/java/org/openmrs/module/kenyaemrml/api/MLUtils.java
api/src/main/java/org/openmrs/module/kenyaemrml/api/service/ModelService.java
api/src/main/java/org/openmrs/module/kenyaemrml/domain/DetailedModelContent.java
api/src/main/java/org/openmrs/module/kenyaemrml/domain/ModelInputFields.java
api/src/main/java/org/openmrs/module/kenyaemrml/domain/ModelSummary.java
api/src/main/java/org/openmrs/module/kenyaemrml/domain/Response.java
api/src/main/java/org/openmrs/module/kenyaemrml/domain/ScoringResult.java
api/src/main/java/org/openmrs/module/kenyaemrml/exception/AdditionalParametersException.java
api/src/main/java/org/openmrs/module/kenyaemrml/exception/EvaluatorCreationException.java
api/src/main/java/org/openmrs/module/kenyaemrml/exception/KeJPMMLEvaluatorException.java
api/src/main/java/org/openmrs/module/kenyaemrml/exception/ModelNotFoundException.java
api/src/main/java/org/openmrs/module/kenyaemrml/exception/ScoringException.java
api/src/main/java/org/openmrs/module/kenyaemrml/exception/StreamProcessorException.java
api/src/main/java/org/openmrs/module/kenyaemrml/exception/SummaryException.java
api/src/main/resources/hts_xgb.pmml
api/src/main/resources/hts_xgb_notimeplace.pmml
omod/pom.xml
omod/src/main/java/org/openmrs/module/kenyaemrml/web/controller/MachineLearningRestController.java
omod/src/main/resources/config.xml
pom.xml

Integrated JPMML
Added API endpoint for scoring a model
Added to the module activator a component that creates a directory to hold ML model resources

Jpmml integration endpoint

---

README.md
api/src/main/java/org/openmrs/module/kenyaemrml/util/MLDataExchange.java
omod/src/main/java/org/openmrs/module/kenyaemrml/fragment/controller/IitRiskScoreHistoryFragmentController.java
omod/src/main/java/org/openmrs/module/kenyaemrml/page/controller/DataManagementPageController.java

Removed some log messages

---

api/src/main/java/org/openmrs/module/kenyaemrml/metadata/MLSeculityMetadata.java
omod/src/main/webapp/pages/dataManagement.gsp

1. Added module privileges and roles to enable normal users access, 
2. update the summary table while pulling to show progress

Privileges Fix

---

api/pom.xml
omod/pom.xml
pom.xml

fix json-simple dependency

---

api/src/main/java/org/openmrs/module/kenyaemrml/iit/PatientRiskScore.java
api/src/main/resources/PatientRiskScore.hbm.xml
api/src/main/resources/liquibase.xml

Added Two columns description and riskFactors to the table

Added Two columns description and riskFactors to the table

---

api/src/main/java/org/openmrs/module/kenyaemrml/util/MLDataExchange.java

[Extract description, riskfactors and evaluationdate from the payload

Extract description, riskfactors and evaluationdate from the payload

---

api/src/main/java/org/openmrs/module/kenyaemrml/util/MLDataExchange.java
omod/src/main/webapp/pages/dataManagement.gsp

1. Modified the get total records from remote to only fetch from the set evaluation date 
2. No need to compare local and remote totals 
3. Frontend enhancements 
4. Some cleanup

Get available records from eval date

---

api/src/main/java/org/openmrs/module/kenyaemrml/util/MLDataExchange.java
omod/src/main/java/org/openmrs/module/kenyaemrml/fragment/controller/IitRiskScoreHistoryFragmentController.java
omod/src/main/webapp/pages/dataManagement.gsp

1. Changed position of progressbar to top of buttons 
2. Removed the initial delay often seen on the progressbar 
3. Fixed the progress count and percentage displayed

Position of progressbar and more enhancements

---

api/src/main/java/org/openmrs/module/kenyaemrml/util/MLDataExchange.java

1. Fixed progress going beyond 100%

1. Fixed progress going beyond 100%

---

api/src/main/java/org/openmrs/module/kenyaemrml/reporting/builder/HighIITRiskPatientsReportBuilder.java

KHP3-1839-IIT report sort by score

KHP3-1839-IIT report sort by score

---

omod/src/main/java/org/openmrs/module/kenyaemrml/fragment/controller/iitRiskScore/IitPatientRiskScoreFragmentController.java

KHP3-1863-RiskFactorsDisplayOnLineList

KHP3-1863-RiskFactorsDisplayOnLineList

---

api/src/main/resources/moduleApplicationContext.xml

Disabled Medium and Low Risk Reports

Disabled Medium and Low Risk Reports

---

api/pom.xml
omod/pom.xml
pom.xml

Bumped Version to 1.1.0

---

api/src/main/java/org/openmrs/module/kenyaemrml/calculation/IITHighRiskScoreCalculation.java
api/src/main/java/org/openmrs/module/kenyaemrml/calculation/IITHighRiskScoreFlagCalculation.java
omod/src/main/java/org/openmrs/module/kenyaemrml/fragment/controller/iitRiskScore/IitPatientRiskScoreFragmentController.java

KHP3-3072 - Invalidate IIT Risk Scores Given Certain Conditions. 
a) if patient has visited since last score, invalidate 
b) if more than one month has passed since last score, invalidate 
c) Change made on 
-patient flag 
-patient page 
-IIT high risk report

KHP3-3072 - Invalidate IIT Risk Scores Given Certain Conditions.

---

api/pom.xml
omod/pom.xml
pom.xml

Bumped to version 1.2.0

---

api/src/main/java/org/openmrs/module/kenyaemrml/api/db/hibernate/HibernateMLinKenyaEMRDao.java
api/src/main/java/org/openmrs/module/kenyaemrml/api/impl/MLinKenyaEMRServiceImpl.java
api/src/main/java/org/openmrs/module/kenyaemrml/api/service/ModelService.java
api/src/main/java/org/openmrs/module/kenyaemrml/util/MLDataExchange.java
omod/src/main/java/org/openmrs/module/kenyaemrml/fragment/controller/IitRiskScoreGeneratorFragmentController.java
omod/src/main/java/org/openmrs/module/kenyaemrml/fragment/controller/iitRiskScore/IitPatientRiskScoreFragmentController.java
omod/src/main/webapp/fragments/iitRiskScoreGenerator.gsp
omod/src/main/webapp/pages/dataManagement.gsp

Add iit pmml model

---

api/src/main/java/org/openmrs/module/kenyaemrml/api/service/ModelService.java
api/src/main/java/org/openmrs/module/kenyaemrml/util/MLDataExchange.java

Filter for HIV program patients only plus better gen error control

Filter for HIV program patients only plus better gen error control

---

api/src/main/java/org/openmrs/module/kenyaemrml/api/MLUtils.java
api/src/main/java/org/openmrs/module/kenyaemrml/api/service/ModelService.java
omod/src/main/java/org/openmrs/module/kenyaemrml/web/controller/MachineLearningRestController.java

Fixed issues with missed appointments variables

Fixed issues with missed appointments variables

---

api/src/main/java/org/openmrs/module/kenyaemrml/api/service/ModelService.java

Fixed issue with timeOnART (days)

Fixed issue with timeOnART (days)

---

api/src/main/java/org/openmrs/module/kenyaemrml/api/service/ModelService.java

Fix: n_visits_lastfive apparently should be total appointments

Fix: n_visits_lastfive apparently should be total appointments

---

api/src/main/java/org/openmrs/module/kenyaemrml/calculation/IITHighRiskScoreFlagCalculation.java
api/src/main/java/org/openmrs/module/kenyaemrml/util/MLDataExchange.java
omod/src/main/java/org/openmrs/module/kenyaemrml/fragment/controller/iitRiskScore/IitPatientRiskScoreFragmentController.java

1. Risk Score Flag only for ART patients 
3. Risk score diplay as a %age 
4. 3. Bulk scores only for current on ART

changes after group review

---

api/pom.xml
api/src/main/java/org/openmrs/module/kenyaemrml/api/MLUtils.java
api/src/main/java/org/openmrs/module/kenyaemrml/api/db/hibernate/HibernateMLinKenyaEMRDao.java
api/src/main/java/org/openmrs/module/kenyaemrml/util/MLDataExchange.java
api/src/main/resources/liquibase.xml
omod/pom.xml
omod/src/main/java/org/openmrs/module/kenyaemrml/fragment/controller/IitRiskScoreGeneratorFragmentController.java
omod/src/main/java/org/openmrs/module/kenyaemrml/fragment/controller/IitRiskScoreHistoryFragmentController.java
omod/src/main/webapp/pages/dataManagement.gsp
pom.xml

Add iit pmml model v5

---

api/src/main/java/org/openmrs/module/kenyaemrml/api/service/ModelService.java

temp add payload log

---

api/src/main/java/org/openmrs/module/kenyaemrml/api/service/ModelService.java

fixed variable most_recent_vl

---

api/src/main/java/org/openmrs/module/kenyaemrml/api/service/ModelService.java

temp enable log

---

api/src/main/resources/liquibase.xml

Modify the size of description field

Modify the size of description field

---

api/pom.xml
api/src/main/java/org/openmrs/module/kenyaemrml/calculation/IITHighRiskScoreFlagCalculation.java
omod/pom.xml
omod/src/main/java/org/openmrs/module/kenyaemrml/fragment/controller/IitRiskScoreGeneratorFragmentController.java
pom.xml

More optimization of iit widget display and flag

More optimization of iit widget display and flag

---

api/src/main/java/org/openmrs/module/kenyaemrml/api/MLinKenyaEMRService.java
api/src/main/java/org/openmrs/module/kenyaemrml/api/impl/MLinKenyaEMRServiceImpl.java
api/src/main/java/org/openmrs/module/kenyaemrml/api/service/ModelService.java
api/src/main/java/org/openmrs/module/kenyaemrml/calculation/IITHighRiskScoreFlagCalculation.java
omod/src/main/java/org/openmrs/module/kenyaemrml/fragment/controller/IitRiskScoreGeneratorFragmentController.java
omod/src/main/java/org/openmrs/module/kenyaemrml/web/controller/MachineLearningRestController.java

Run time enhancements:
1. Update score in DB instead of adding a new one
2. Update score only if the greencard has been filled or on the very first time

Run time enhancements

---

api/src/main/java/org/openmrs/module/kenyaemrml/api/impl/MLinKenyaEMRServiceImpl.java
api/src/main/java/org/openmrs/module/kenyaemrml/calculation/IITHighRiskScoreFlagCalculation.java
api/src/main/java/org/openmrs/module/kenyaemrml/util/MLDataExchange.java
omod/src/main/java/org/openmrs/module/kenyaemrml/fragment/controller/IitRiskScoreGeneratorFragmentController.java
omod/src/main/resources/config.xml

Added ability to enable and disable IIT ML on global properties

Added ability to enable and disable IIT ML on global properties

---

omod/src/main/java/org/openmrs/module/kenyaemrml/fragment/controller/IitRiskScoreGeneratorFragmentController.java

fixed IIT widget

---

api/pom.xml
omod/pom.xml
pom.xml

Bumped to V1.3.3

---

api/src/main/java/org/openmrs/module/kenyaemrml/calculation/IITHighRiskScoreFlagCalculation.java
api/src/main/java/org/openmrs/module/kenyaemrml/task/GenerateIITMLPredictionsTask.java
api/src/main/java/org/openmrs/module/kenyaemrml/util/MLDataExchange.java
api/src/main/resources/liquibase.xml
omod/src/main/java/org/openmrs/module/kenyaemrml/fragment/controller/IitRiskScoreGeneratorFragmentController.java
omod/src/main/resources/config.xml

Added a new scheduled task for IIT ML to run every day at 3pm

Added a new scheduled task for IIT ML to run every day at 3pm

---

api/src/main/java/org/openmrs/module/kenyaemrml/api/IITMLService.java
api/src/main/java/org/openmrs/module/kenyaemrml/api/impl/IITMLServiceImpl.java
api/src/main/java/org/openmrs/module/kenyaemrml/api/service/ModelService.java
api/src/main/resources/moduleApplicationContext.xml

More optimization:
1. IIT model loaded only once during system startup
2. Reduced RAM consumption from 22MB per patient to 0 (zero) MB per patient
3. This is work in progress

More optimization

---

api/src/main/java/org/openmrs/module/kenyaemrml/api/service/ModelService.java

Cleanup after service optimization

Cleanup after service optimization

---

api/pom.xml
api/src/main/java/org/openmrs/module/kenyaemrml/api/impl/HTSMLServiceImpl.java
omod/pom.xml
omod/src/main/java/org/openmrs/module/kenyaemrml/web/controller/MachineLearningRestController.java
pom.xml

KHP3-829 more friendly error on missing facility
Bump version to 1.3.4

KHP3-829 more friendly error

---

api/src/main/unfiltered-resources/hts/hts_ml_facility_cut_off_national_oct_2023.json
api/src/main/unfiltered-resources/iit/hts_ml_facility_cut_off_national_oct_2023.json

Fixed the cutoffs for the 2 added facilities to remove spaces

Fixed the cutoffs for the 2 added facilities to remove spaces

---

api/src/main/java/org/openmrs/module/kenyaemrml/calculation/IITHighRiskScoreCalculation.java
api/src/main/java/org/openmrs/module/kenyaemrml/util/MLDataExchange.java

Fixed the IIT ML High Risk Report issue with patients not on ART

Fixed the IIT ML High Risk Report issue with patients not on ART

---

api/pom.xml
omod/pom.xml
pom.xml

Bumped to version 1.3.7

---

api/src/main/java/org/openmrs/module/kenyaemrml/calculation/IITHighRiskScoreCalculation.java
api/src/main/java/org/openmrs/module/kenyaemrml/util/MLDataExchange.java
omod/src/main/webapp/pages/dataManagement.gsp

Khp3 5641 new get current on art query and disable ndwh pull for 3.x

KHP3-5641-NewGetCurrentOnARTQueryAndDisableNDWHPull-3.x

---

api/src/main/java/org/openmrs/module/kenyaemrml/api/impl/ModelServiceImpl.java
api/src/main/java/org/openmrs/module/kenyaemrml/calculation/IITHighRiskScoreCalculation.java
api/src/main/java/org/openmrs/module/kenyaemrml/util/MLDataExchange.java

IIT ML Optimized Code by code reuse for various vars

IIT ML Optimized Code by code reuse for various vars

---

api/pom.xml
api/src/main/resources/moduleApplicationContext.xml
omod/pom.xml
pom.xml

Removed High Risk Report and Bumped to version 1.3.8

Removed High Risk Report and Bumped to version 1.3.8

---

api/src/main/resources/moduleApplicationContext.xml

Disable High IIT risk report

---

omod/src/main/java/org/openmrs/module/kenyaemrml/web/controller/CorsInterceptor.java

Remove some logging messages

---

api/pom.xml
omod/pom.xml
pom.xml

Bump version to 1.4.1-SNAPSHOT

(chore) : Bump version to 1.4.1-SNAPSHOT

---

api/src/main/java/org/openmrs/module/kenyaemrml/ModuleConstants.java
api/src/main/java/org/openmrs/module/kenyaemrml/api/MLUtils.java
api/src/main/java/org/openmrs/module/kenyaemrml/api/impl/MLinKenyaEMRServiceImpl.java
api/src/main/unfiltered-resources/iit/iit_ml_facility_cut_off_national_dec_2023.json

Add iit score as an obs

---

api/pom.xml
api/src/main/java/org/openmrs/module/kenyaemrml/ModuleConstants.java
api/src/main/java/org/openmrs/module/kenyaemrml/api/MLUtils.java
api/src/main/java/org/openmrs/module/kenyaemrml/api/impl/MLinKenyaEMRServiceImpl.java
api/src/main/java/org/openmrs/module/kenyaemrml/api/impl/ModelServiceImpl.java
omod/pom.xml
omod/src/main/java/org/openmrs/module/kenyaemrml/web/controller/MachineLearningRestController.java
omod/src/main/resources/config.xml
pom.xml

Fetch IIT scores from remote API

Fetch IIT scores from remote API
